# Generated by Django 2.2.2 on 2019-06-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codMedicamento', models.CharField(help_text='Ingrese el codigo del Medicamento', max_length=10)),
                ('nomMededicamento', models.CharField(help_text='Ingrese el nombre del Medicamento', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codMedico', models.CharField(help_text='Ingrese el codigo del Medico', max_length=10)),
                ('nomMedico', models.CharField(help_text='Ingrese el nombre del Medico', max_length=200)),
            ],
        ),
    ]
