# Generated by Django 2.2.2 on 2019-06-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codServicio', models.CharField(help_text='Ingrese el codigo del Servicio', max_length=10)),
                ('nomServicio', models.CharField(help_text='Ingrese el nombre del Servicio', max_length=200)),
                ('preServicio', models.DecimalField(decimal_places=2, help_text='Ingrese el precio del Servicio', max_digits=5)),
            ],
        ),
    ]
