# Generated by Django 2.2.1 on 2019-06-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='codMedicamento',
            field=models.IntegerField(help_text='Ingrese el codigo del Medicamento', max_length=10, primary_key=True, serialize=False),
        ),
    ]
