# Generated by Django 2.2.1 on 2019-06-19 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0002_auto_20190618_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citasyconsultas.Usuario'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='codMedicamento',
            field=models.IntegerField(help_text='Ingrese el codigo del Medicamento', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medico',
            name='codMedico',
            field=models.IntegerField(help_text='Ingrese el codigo del Medico', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('codSec', models.IntegerField(help_text='Ingrese el codigo de la Secretaria', max_length=10, primary_key=True, serialize=False)),
                ('nomSec', models.CharField(help_text='Ingrese el nombre de la Secretaria', max_length=200)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citasyconsultas.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('codCon', models.IntegerField(primary_key=True, serialize=False)),
                ('diagnostico', models.CharField(help_text='Ingrese el diagnostico', max_length=500)),
                ('dosis', models.CharField(help_text='Ingrese la dosis', max_length=500)),
                ('medicamentos', models.ManyToManyField(to='citasyconsultas.Medicamento')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citasyconsultas.Medico')),
                ('servicios', models.ManyToManyField(to='citasyconsultas.Servicio')),
            ],
        ),
    ]
