# Generated by Django 2.2.2 on 2019-06-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0002_servicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='codServicio',
            new_name='codSer',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='nomServicio',
            new_name='nomSer',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='preServicio',
            new_name='preSer',
        ),
    ]
