# Generated by Django 2.2.2 on 2019-06-19 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0003_auto_20190618_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('numDep', models.IntegerField(primary_key=True, serialize=False)),
                ('nomDep', models.CharField(help_text='Ingrese un departamento', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('numExpediente', models.IntegerField(primary_key=True, serialize=False)),
                ('nomPaciente', models.CharField(help_text='Ingrese el nombre del paciente', max_length=200)),
                ('apelPaciente', models.CharField(help_text='Ingrese el apellido del paciente', max_length=200)),
                ('fechaNacimiento', models.DateField()),
                ('emailPaciente', models.CharField(help_text='Ingrese eMail del paciente', max_length=200)),
                ('telefono', models.CharField(help_text='Ingrese el telefono del paciente', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('numMunicipio', models.IntegerField(primary_key=True, serialize=False)),
                ('nomMunicipio', models.CharField(help_text='Ingrese un municipio', max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citasyconsultas.Departamento')),
            ],
        ),
    ]
