# Generated by Django 2.2.2 on 2019-06-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0003_auto_20190617_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codUsu', models.CharField(help_text='Ingrese el Usuario, maximo 10 caracteres', max_length=10, primary_key=True, serialize=False)),
                ('pasUsu', models.CharField(help_text='Ingrese contraseña, maximo 20 caracteres', max_length=20)),
                ('tipo_usuario', models.CharField(blank=True, choices=[('s', 'Secretaria'), ('m', 'Medico')], default='s', help_text='Tipo de usuario en el sistema', max_length=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['codSer', 'preSer']},
        ),
        migrations.RenameField(
            model_name='medicamento',
            old_name='nomMededicamento',
            new_name='nomMedicamento',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='id',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='id',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='id',
        ),
        migrations.AddField(
            model_name='servicio',
            name='duraci',
            field=models.DurationField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='codMedicamento',
            field=models.CharField(help_text='Ingrese el codigo del Medicamento', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medico',
            name='codMedico',
            field=models.CharField(help_text='Ingrese el codigo del Medico', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='codSer',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nomSer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='preSer',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
