# Generated by Django 2.2.1 on 2019-06-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0004_auto_20190618_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='horCon',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='codMedico',
            field=models.IntegerField(help_text='Ingrese el codigo del Medico', primary_key=True, serialize=False),
        ),
    ]
