# Generated by Django 2.2.2 on 2019-06-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0004_auto_20190617_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='duraci',
            field=models.IntegerField(),
        ),
    ]
