# Generated by Django 2.2.1 on 2019-06-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0004_departamento_municipio_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ManyToManyField(help_text='Seleccione el paciente', to='citasyconsultas.Paciente'),
        ),
    ]
