# Generated by Django 2.2.1 on 2019-06-18 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0002_auto_20190617_0552'),
        ('citasyconsultas', '0005_auto_20190617_1708'),
    ]

    operations = [
    ]
