# Generated by Django 2.2.1 on 2019-06-21 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0005_consulta_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='paciente',
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(help_text='Seleccione el paciente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='citasyconsultas.Paciente'),
        ),
    ]
