# Generated by Django 2.2.1 on 2019-06-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0006_auto_20190621_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='codMedico',
            field=models.IntegerField(help_text='Ingrese el codigo del Medico', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='codSec',
            field=models.IntegerField(help_text='Ingrese el codigo de la Secretaria', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='codSer',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
