# Generated by Django 2.2.1 on 2019-06-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0006_merge_20190617_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ('codSer',)},
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='preSer',
            new_name='precio',
        ),
        migrations.AlterField(
            model_name='cita',
            name='apePac',
            field=models.CharField(help_text='Ingrese los apellidos, solo letras', max_length=255),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecCon',
            field=models.DateTimeField(help_text='Seleccione una fecha para la cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='nomPac',
            field=models.CharField(help_text='Ingrese los nombres, solo letras', max_length=255),
        ),
        migrations.AlterField(
            model_name='cita',
            name='telPac',
            field=models.IntegerField(help_text='Solo numeros', unique=True),
        ),
    ]
