# Generated by Django 2.2.1 on 2019-06-21 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0007_auto_20190620_2053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CitaServicio',
        ),
    ]
