# Generated by Django 2.2.1 on 2019-06-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0005_consulta_paciente'),
        ('citasyconsultas', '0008_delete_citaservicio'),
    ]

    operations = [
    ]
