# Generated by Django 2.2.1 on 2019-06-21 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0007_auto_20190621_1017'),
        ('citasyconsultas', '0009_merge_20190621_0841'),
    ]

    operations = [
    ]
