# Generated by Django 2.2.1 on 2019-06-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0010_auto_20190621_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
