# Generated by Django 2.2.1 on 2019-06-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0011_auto_20190621_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
    ]
