# Generated by Django 2.2.1 on 2019-06-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0011_auto_20190621_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='estCon',
            field=models.IntegerField(default=0),
        ),
    ]
