# Generated by Django 2.2.1 on 2019-06-21 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0013_auto_20190621_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='depResidencia',
            field=models.ForeignKey(default='10', on_delete=django.db.models.deletion.PROTECT, to='citasyconsultas.Departamento'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='munResidencia',
            field=models.ForeignKey(default='15', on_delete=django.db.models.deletion.PROTECT, to='citasyconsultas.Municipio'),
        ),
    ]
