# Generated by Django 2.2.1 on 2019-06-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0014_auto_20190621_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='diagnostico',
            field=models.CharField(help_text='Ingrese el diagnostico', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='dosis',
            field=models.CharField(help_text='Ingrese la dosis', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='medicamentos',
            field=models.ManyToManyField(null=True, to='citasyconsultas.Medicamento'),
        ),
    ]
