# Generated by Django 2.2.1 on 2019-06-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0015_auto_20190621_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='emailPaciente',
            field=models.EmailField(help_text='Ingrese eMail del paciente', max_length=200),
        ),
    ]
