# Generated by Django 2.2.1 on 2019-06-22 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0015_auto_20190621_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='fecConHoy',
            field=models.DateField(default=datetime.date(2019, 6, 22)),
        ),
    ]
