# Generated by Django 2.2.1 on 2019-06-22 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0016_auto_20190621_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='apePac',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='nomPac',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='telPac',
        ),
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.IntegerField(help_text='Pendiente = 0 ,  Completado = 1', null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='pacien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='citasyconsultas.Paciente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecCon',
            field=models.DateField(help_text='Seleccione la fecha para la cita', null=True),
        ),
        migrations.RemoveField(
            model_name='cita',
            name='servic',
        ),
        migrations.AddField(
            model_name='cita',
            name='servic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='citasyconsultas.Servicio'),
        ),
    ]
