# Generated by Django 2.2.1 on 2019-06-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0016_consulta_fecconhoy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fecConHoy',
            field=models.DateField(),
        ),
    ]
