# Generated by Django 2.2.1 on 2019-06-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0017_auto_20190621_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fecConHoy',
            field=models.DateField(auto_now_add=True),
        ),
    ]
