# Generated by Django 2.2.1 on 2019-06-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0018_auto_20190621_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='diagnostico',
            field=models.CharField(blank=True, help_text='Ingrese el diagnostico', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='dosis',
            field=models.CharField(blank=True, help_text='Ingrese la dosis', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='fecConHoy',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='medicamentos',
            field=models.ManyToManyField(blank=True, null=True, to='citasyconsultas.Medicamento'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='servicios',
            field=models.ManyToManyField(blank=True, to='citasyconsultas.Servicio'),
        ),
    ]
