# Generated by Django 2.2.1 on 2019-06-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0019_auto_20190622_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.IntegerField(help_text='Pendiente = 0 ,  Completado = 1', null=True),
        ),
    ]
