# Generated by Django 2.2.1 on 2019-06-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0021_auto_20190622_0954'),
        ('citasyconsultas', '0020_auto_20190622_0143'),
    ]

    operations = [
    ]
