# Generated by Django 2.2.1 on 2019-06-22 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0022_merge_20190622_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='estCon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.IntegerField(default=0, help_text='Pendiente = 0 ,  Completado = 1', null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='pacien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='citasyconsultas.Paciente'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='medicamentos',
            field=models.ManyToManyField(to='citasyconsultas.Medicamento'),
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='servicios',
        ),
        migrations.AddField(
            model_name='consulta',
            name='servicios',
            field=models.ManyToManyField(to='citasyconsultas.Servicio'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='emailPaciente',
            field=models.CharField(help_text='Ingrese eMail del paciente', max_length=200),
        ),
    ]
