# Generated by Django 2.2.1 on 2019-06-23 02:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0023_auto_20190622_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='medico',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='diagnostico',
            field=models.CharField(blank=True, default=django.db.models.deletion.SET_NULL, help_text='Ingrese el diagnostico', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='dosis',
            field=models.CharField(blank=True, default=django.db.models.deletion.SET_NULL, help_text='Ingrese la dosis', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='fecConHoy',
            field=models.DateField(default=datetime.date(2019, 6, 22)),
        ),
    ]
