# Generated by Django 2.2.1 on 2019-06-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0023_auto_20190622_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
