# Generated by Django 2.2.1 on 2019-06-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0024_auto_20190622_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='diagnostico',
            field=models.CharField(blank=True, help_text='Ingrese el diagnostico', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='dosis',
            field=models.CharField(blank=True, help_text='Ingrese la dosis', max_length=500, null=True),
        ),
    ]
