# Generated by Django 2.2.1 on 2019-06-23 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0024_auto_20190622_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cita',
            options={},
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.IntegerField(default=0, help_text='Pendiente = 0,  Completado = 1', null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecCon',
            field=models.DateField(help_text=' ', null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='horCon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='citasyconsultas.Horario'),
        ),
    ]
