# Generated by Django 2.2.1 on 2019-06-23 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0025_auto_20190622_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='estCon',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='medicamentos',
            field=models.ManyToManyField(blank=True, null=True, to='citasyconsultas.Medicamento'),
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='servicios',
        ),
        migrations.AddField(
            model_name='consulta',
            name='servicios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citasyconsultas.Servicio'),
        ),
    ]
