# Generated by Django 2.2.2 on 2019-06-23 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0026_auto_20190622_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fecConHoy',
            field=models.DateField(default=datetime.date(2019, 6, 23)),
        ),
    ]
