# Generated by Django 2.2.1 on 2019-06-23 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0027_auto_20190623_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fecCitHoy',
            field=models.DateField(default=datetime.date(2019, 6, 23)),
        ),
    ]
