# Generated by Django 2.2.1 on 2019-06-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0027_auto_20190623_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='numCit',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
