# Generated by Django 2.2.1 on 2019-06-24 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0028_auto_20190623_0820'),
        ('citasyconsultas', '0028_cita_feccithoy'),
    ]

    operations = [
    ]
