# Generated by Django 2.2.2 on 2019-06-24 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0029_merge_20190624_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecCitHoy',
            field=models.DateField(default=datetime.date(2019, 6, 24)),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='fecConHoy',
            field=models.DateField(default=datetime.date(2019, 6, 24)),
        ),
    ]
