# Generated by Django 2.2.1 on 2019-06-27 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0030_auto_20190624_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecCitHoy',
            field=models.DateField(default=datetime.date(2019, 6, 26)),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='fecConHoy',
            field=models.DateField(default=datetime.date(2019, 6, 26)),
        ),
    ]
