# Generated by Django 2.2.1 on 2019-07-04 00:25

import citasyconsultas.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0032_remove_cita_feccithoy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fecConHoy',
            field=models.DateField(default=datetime.date(2019, 7, 3)),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apelPaciente',
            field=models.CharField(help_text='Ingrese el apellido del paciente', max_length=200, validators=[citasyconsultas.validators.valid_Apellidos]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nomPaciente',
            field=models.CharField(help_text='Ingrese el nombre del paciente', max_length=200, validators=[citasyconsultas.validators.valid_Nombres]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=8, unique=True, validators=[citasyconsultas.validators.valid_Telefono]),
        ),
    ]
