# Generated by Django 2.2.1 on 2019-07-04 00:29

import citasyconsultas.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0034_auto_20190703_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(help_text='Solo numeros', max_length=8, validators=[citasyconsultas.validators.valid_Telefono]),
        ),
    ]
