# Generated by Django 2.2.1 on 2019-07-08 00:49

import citasyconsultas.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0035_auto_20190703_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ('numCit',)},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'ordering': ('nomMunicipio',)},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ('nomSer',)},
        ),
        migrations.AddField(
            model_name='cita',
            name='citId',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='numCit',
            field=models.CharField(help_text='Numero de cita del dia', max_length=2, validators=[citasyconsultas.validators.valid_Telefono]),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='fecConHoy',
            field=models.DateField(default=datetime.date(2019, 7, 7)),
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('fecCon', 'horCon')},
        ),
    ]
