# Generated by Django 2.2.1 on 2019-07-08 01:37

import citasyconsultas.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0036_auto_20190707_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(help_text='Solo numeros', max_length=8, unique=True, validators=[citasyconsultas.validators.valid_Telefono]),
        ),
    ]
