# Generated by Django 2.2.1 on 2019-07-08 02:19

import citasyconsultas.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0037_auto_20190707_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='citId',
        ),
        migrations.AlterField(
            model_name='cita',
            name='numCit',
            field=models.CharField(help_text='Numero de cita del dia', max_length=2, primary_key=True, serialize=False, validators=[citasyconsultas.validators.valid_Telefono]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(help_text='Solo numeros', max_length=8, validators=[citasyconsultas.validators.valid_Telefono]),
        ),
        migrations.AlterUniqueTogether(
            name='paciente',
            unique_together={('telefono',)},
        ),
    ]
