# Generated by Django 2.2.1 on 2019-07-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0038_auto_20190707_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='numCit',
            field=models.IntegerField(help_text='Numero de cita del dia', primary_key=True, serialize=False),
        ),
    ]
