# Generated by Django 2.2.1 on 2019-07-09 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0039_auto_20190707_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fecConHoy',
            field=models.DateField(default=datetime.date(2019, 7, 9)),
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together=set(),
        ),
    ]
