# Generated by Django 2.2.1 on 2019-07-09 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0040_auto_20190709_1144'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('fecCon', 'horCon')},
        ),
    ]
