# Generated by Django 2.2.1 on 2019-07-09 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citasyconsultas', '0043_auto_20190709_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecCon',
            field=models.DateField(null=True, verbose_name='Fecha de Cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='horCon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='citasyconsultas.Horario', verbose_name='Hora de Cita'),
        ),
    ]
